tap "adoptopenjdk/openjdk"
tap "cjbassi/ytop"
tap "github/gh"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
tap "jesseduffield/lazydocker"
brew "atuin"
brew "autoconf"
brew "automake"
brew "bat"
brew "xz"
brew "python@3.9"
brew "glib"
brew "pkg-config"
brew "lzo"
brew "cairo"
brew "libtool"
brew "cask"
brew "cmake"
brew "cmocka"
brew "ctop"
brew "dos2unix"
brew "doxygen"
brew "exa"
brew "fzf"
brew "gdb"
brew "git-extras"
brew "gnupg"
brew "go"
brew "gobject-introspection"
brew "golangci-lint"
brew "harfbuzz"
brew "pango"
brew "graphviz"
brew "grex"
brew "makensis"
brew "man2html"
brew "mas"
brew "maven"
brew "mingw-w64"
brew "mockery"
brew "mono", link: false
brew "node"
brew "pre-commit", link: false
brew "pyenv"
brew "pyenv-virtualenv"
brew "python@3.8"
brew "starship"
brew "truncate", link: false
brew "wget"
brew "yarn"
brew "heroku/brew/heroku"
brew "jesseduffield/lazydocker/lazydocker"
mas "com.adriangranados.wifiexplorerlite", id: 1408727408
mas "GarageBand", id: 682658836
mas "GoodNotes", id: 1444383602
mas "iMovie", id: 408981434
mas "Irvue", id: 1039633667
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "NordVPN IKE", id: 1116599239
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Session", id: 1521432881
mas "Slack", id: 803453959
mas "Spark", id: 1176895641
mas "Telegram", id: 747648890
mas "The Unarchiver", id: 425424353
mas "Toggl Track", id: 957734279
mas "Xcode", id: 497799835
