#!/usr/bin/env bash

mkdir -p $HOME/.config
mkdir -p $HOME/.hammerspoon

echo " Applying symlinks"
ln -sf "$DOTFILES_PATH"/procs/.procs.toml "$HOME"/.procs.toml
ln -sf "$DOTFILES_PATH"/vim/.vimrc "$HOME"/.vimrc
ln -sf "$DOTFILES_PATH"/git/.gitconfig "$HOME"/.gitconfig
ln -sf "$DOTFILES_PATH"/git/.gitignore "$HOME"/.gitignore
ln -sf "$DOTFILES_PATH"/git/.gitattributes "$HOME"/.gitattributes
ln -sf "$DOTFILES_PATH"/starship/starship.toml "$HOME"/.config/starship.toml
ln -sf "$DOTFILES_PATH"/hammerspoon/init.lua "$HOME"/.hammerspoon/init.lua
ln -sf "$DOTFILES_PATH"/zsh/.zshrc "$HOME"/.zshrc
ln -sf "$DOTFILES_PATH"/zsh/.zshenv "$HOME"/.zshenv
ln -sf "$DOTFILES_PATH"/zim/.zlogin "$HOME"/.zlogin
ln -sf "$DOTFILES_PATH"/zim/.zimrc "$HOME"/.zimrc
