alias devs="./.scripts/devs.sh"
alias check="make"
alias finish-release="./.scripts/ci/finish-release"
alias tw="npm run test -- --watch"
#alias n="nvm use"
alias n="fnm use"
alias nd="fnm use default"
