#!/usr/bin/env bash

set -uo pipefail

brew services stop --all
brew bundle dump --file="${HOMEBREW_BUNDLE_FILE_PATH}" --force
echo 'Brew apps exported!'

pip freeze >"$DOTFILES_PATH/langs/python/requirements.txt"
echo 'Python apps exported!'

if [ -d "$PRIVATE_FOLDER" ]; then
  echo "Sync private files to private folder"
  mkdir -p "$PRIVATE_FOLDER/zsh/exports"
  mkdir -p "$PRIVATE_FOLDER/zsh/aliases"
  cp "$DOTFILES_PATH/zsh/exports/private-exports.sh" "$PRIVATE_FOLDER/zsh/exports/private-exports.sh"
  cp "$DOTFILES_PATH/zsh/aliases/private-aliases.sh" "$PRIVATE_FOLDER/zsh/aliases/private-aliases.sh"
fi

cd "$DOTFILES_PATH" || exit
git pull
git add .
git commit -m "Checkpoint $(date +"%d_%m_%Y")"
git push -u origin main

echo " 👌 Done"
