#!/usr/bin/env bash

set -eo pipefail

DOTFILES_PATH=$HOME/.dotfiles

source "$DOTFILES_PATH/shell/sout"
source "$DOTFILES_PATH/shell/os"
source "$DOTFILES_PATH/.scripts/utils"

sout::info " 👾 ZSH as the default shell"
chsh -s $(which zsh)

echo " 🍉 Installing zim"
if [ ! -d "$HOME/.zim" ]; then
  curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh
else
  echo " 🍉 Already installed"
fi

if [ ! -d "$HOME/.utilsh" ]; then
  if [ -z "$UTILSH_PATH" ]; then
    echo " 🧢 Installing utilsh"
    git clone --depth 1 git@github.com:raulanatol/utilsh.git "$HOME/.utilsh"
  fi
fi

if os::is_macos; then
  sout::info "Installing MacOS 🍎 custom packages"
  utils::install_macos
fi

source "$DOTFILES_PATH/misc/install.sh"

sout::info " 👌 Done. Reboot needed!"
